all:
	#sudo gcc eccFunctionTest.c -o test -I../../openssl-1.0.2a/include -I../../openssl-fips-2.0.9/fips  -L../../openssl-1.0.2a/ -lcrypto	-ld
	#sudo gcc eccFunctionTest.c -o test -I../../openssl-fips-2.0.9/include -I../../openssl-fips-2.0.9/fips  -L../../openssl-fips-2.0.9/ -lcrypto
	sudo gcc eccFunctionTest.c -o test -I../../openssl-1.0.1e/include  -L../../openssl-1.0.1e/ -lcrypto -ldl

